services:
  net:
    image: alpine:latest
    command: /bin/sh -c "tail -f /dev/null"
  # mongo:
  #   image: mongo:6
  #   volumes:
  #     - ../data:/data/db
  #   network_mode: service:net
  # redis:
  #   image: redis:7
  #   network_mode: service:net
  dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "tail -f /dev/null"
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh:/home/user/.ssh
      - $HOME/.aws:/home/user/.aws
      - $HOME/.gitconfig:/home/user/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock:rw
    network_mode: service:net
